repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: git@github.com:asottile/reorder-python-imports.git
    rev: v3.14.0
    hooks:
    -   id: reorder-python-imports
        args: ["--py39-plus", "--add-import", "from __future__ import annotations"]

-   repo: git@github.com:psf/black.git
    rev: 23.1.0
    hooks:
    -   id: black
        args: ["--line-length=79"]

-   repo: git@github.com:PyCQA/flake8.git
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: ["--ignore=E203,E501,W503"]

-   repo: git@github.com:pre-commit/mirrors-mypy.git
    rev: v1.13.0
    hooks:
    -   id: mypy
        args:
            - --ignore-missing-imports
        additional_dependencies: ["types-pyyaml"]
