version: '3.4'

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.5
    ports:
      - 8080:8080    # REST API port
      - 50051:50051  # gRPC API port
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'  # Enable modules loaded via API
      ENABLE_GRPC_API: 'true'           # Enable gRPC API
      CLUSTER_HOSTNAME: 'node1'
      LOG_LEVEL: 'debug'                # Set log level to debug to see detailed logs
    networks:
      - chatbot-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - chatbot-network

volumes:
  weaviate_data:

networks:
  chatbot-network:
    driver: bridge
